[2019-01-10 20:15:14,704: CRITICAL/MainProcess] Unrecoverable error: RuntimeError("Model class django_celery_results.models.TaskResult doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.",)
Traceback (most recent call last):
  File "/var/www/dark_web/myenv/lib/python3.5/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/dark_web/myenv/lib/python3.5/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/var/www/dark_web/myenv/lib/python3.5/site-packages/celery/bootsteps.py", line 115, in start
    self.on_start()
  File "/var/www/dark_web/myenv/lib/python3.5/site-packages/celery/apps/worker.py", line 139, in on_start
    self.emit_banner()
  File "/var/www/dark_web/myenv/lib/python3.5/site-packages/celery/apps/worker.py", line 154, in emit_banner
    ' \n', self.startup_info(artlines=not use_image))),
  File "/var/www/dark_web/myenv/lib/python3.5/site-packages/celery/apps/worker.py", line 217, in startup_info
    results=self.app.backend.as_uri(),
  File "/var/www/dark_web/myenv/lib/python3.5/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/var/www/dark_web/myenv/lib/python3.5/site-packages/celery/app/base.py", line 1196, in backend
    return self._get_backend()
  File "/var/www/dark_web/myenv/lib/python3.5/site-packages/celery/app/base.py", line 914, in _get_backend
    self.loader)
  File "/var/www/dark_web/myenv/lib/python3.5/site-packages/celery/app/backends.py", line 70, in by_url
    return by_name(backend, loader), url
  File "/var/www/dark_web/myenv/lib/python3.5/site-packages/celery/app/backends.py", line 50, in by_name
    cls = symbol_by_name(backend, aliases)
  File "/var/www/dark_web/myenv/lib/python3.5/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/var/www/dark_web/myenv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/var/www/dark_web/myenv/lib/python3.5/site-packages/django_celery_results/backends/__init__.py", line 4, in <module>
    from .database import DatabaseBackend
  File "/var/www/dark_web/myenv/lib/python3.5/site-packages/django_celery_results/backends/database.py", line 6, in <module>
    from ..models import TaskResult
  File "/var/www/dark_web/myenv/lib/python3.5/site-packages/django_celery_results/models.py", line 18, in <module>
    class TaskResult(models.Model):
  File "/var/www/dark_web/myenv/lib/python3.5/site-packages/django/db/models/base.py", line 95, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class django_celery_results.models.TaskResult doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
